# Generated by Django 5.2.4 on 2025-08-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazaliste', '0002_predstava'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dvorana', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predstava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raspored', to='kazaliste.predstava')),
            ],
            options={
                'ordering': ['date', 'time', 'predstava__title'],
            },
        ),
    ]
