# Generated by Django 5.2.4 on 2025-08-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazaliste', '0005_priceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'Nova rezervacija'), ('contacted', 'Kontaktirana osoba'), ('closed', 'Zatvorena rezervacija')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predstava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kazaliste.predstava')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
