# Generated by Django 5.2.4 on 2025-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazaliste', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('new', 'Nova rezervacija'), ('closed', 'Zatvorena rezervacija')], default='new', max_length=20),
        ),
    ]
