# Generated by Django 5.2.4 on 2025-08-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazaliste', '0007_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('poslana', 'Rezervacija poslana'), ('closed', 'Zatvorena rezervacija')], default='new', max_length=20),
        ),
    ]
